name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        ROS_DISTRO: ["noetic"]
    runs-on: ubuntu-latest
    steps:
      - uses: smilerobotics/actions-ros-bloom-generate@v1
        with:
          repository_owner: smilerobotics
          repository: laser_filters
          ref: smilerobotics-devel
          ros_distro: ${{ matrix.ROS_DISTRO }}
          targets: ./laser_filters
          name_prefix: ${{ matrix.ROS_DISTRO }}-
          repository_type: github
