name: Check update

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_updated: ${{ steps.check.outputs.is_updated }}
    steps:
      - name: check
        uses: smilerobotics/actions-check-github-repository-update@v1
        id: check
        with:
          repository: smilerobotics/laser_filters
          ref: smilerobotics-devel
          working_directory: .
          command_output: ~/smilerobotics-devel
          cache_key_prefix: smilerobotics-devel
  build:
    needs: [check]
    if: ${{ needs.check.outputs.is_updated == 'true' }}
    uses: smilerobotics/ros-bloom-generate-smilerobotics-laser-filters/.github/workflows/build.yml@main
